from __future__ import annotations

import os
import subprocess
from getpass import getpass
from pathlib import Path

from rich.console import Console

console = Console()


def detect_timezone() -> str:
    # 1) /etc/timezone (common on Debian/Ubuntu)
    try:
        p = Path("/etc/timezone")
        if p.exists():
            v = p.read_text().strip()
            if v:
                return v
    except Exception:
        pass

    # 2) timedatectl
    try:
        out = subprocess.check_output(["timedatectl", "show", "-p", "Timezone", "--value"], text=True).strip()
        if out:
            return out
    except Exception:
        pass

    return "UTC"


def run_init(*, env_path: str = ".env") -> int:
    env_file = Path(env_path)
    if env_file.exists():
        console.print(f"[yellow]{env_path} already exists.[/yellow]")
        overwrite = input("Overwrite? (y/N): ").strip().lower() == "y"
        if not overwrite:
            console.print("Cancelled.")
            return 1

    default_base = os.getenv("CANVAS_BASE_URL", "https://canvas.ubc.ca")
    default_tz = os.getenv("TIMEZONE") or detect_timezone()
    default_db = os.getenv("DB_PATH", "./data/agent.db")

    console.print("Canvas Course Agent init")

    base = input(f"Canvas base URL [{default_base}]: ").strip() or default_base
    if base.endswith("/"):
        base = base[:-1]

    tz = input(f"Display timezone (IANA, e.g. America/Vancouver) [{default_tz}]: ").strip() or default_tz

    db = input(f"SQLite DB path [{default_db}]: ").strip() or default_db

    console.print("Canvas access token (input hidden)")
    token = getpass("CANVAS_ACCESS_TOKEN: ").strip()
    if not token:
        console.print("[red]Token is required.[/red]")
        return 1

    content = (
        "# Generated by canvas-agent init\n"
        f"CANVAS_BASE_URL={base}\n"
        f"CANVAS_ACCESS_TOKEN={token}\n"
        f"DB_PATH={db}\n"
        f"TIMEZONE={tz}\n"
    )

    env_file.write_text(content)
    try:
        os.chmod(env_file, 0o600)
    except Exception:
        pass

    console.print(f"[green]Wrote {env_path}[/green]")
    console.print("Next: canvas-agent healthcheck")
    return 0
